// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <glade/glade.h>
#include <glade/glade-parser.h>

static const gchar *__prefix = "__gtksharp_";

#define HAS_PREFIX(a) (*((guint64 *)(a)) == *((guint64 *) __prefix))

static GObjectClass *
get_threshold_class (GObject *obj)
{
	GType gtype = G_TYPE_FROM_INSTANCE (obj);
	while (HAS_PREFIX (g_type_name (gtype)))
		gtype = g_type_parent (gtype);
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL) klass = g_type_class_ref (gtype);
	return klass;
}

gboolean gladesharp_glade_signalinfo_get_after (GladeSignalInfo *signalinfo);
void gladesharp_glade_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value);

gboolean
gladesharp_glade_signalinfo_get_after (GladeSignalInfo *signalinfo)
{
	return (gboolean)signalinfo->after;
}

void
gladesharp_glade_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value)
{
	signalinfo->after = (gboolean)value;
}

