// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <gdk/gdk.h>

static const gchar *__prefix = "__gtksharp_";

#define HAS_PREFIX(a) (*((guint64 *)(a)) == *((guint64 *) __prefix))

static GObjectClass *
get_threshold_class (GObject *obj)
{
	GType gtype = G_TYPE_FROM_INSTANCE (obj);
	while (HAS_PREFIX (g_type_name (gtype)))
		gtype = g_type_parent (gtype);
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL) klass = g_type_class_ref (gtype);
	return klass;
}

guint gdksharp_gdk_colormap_get_size_offset (void);

guint
gdksharp_gdk_colormap_get_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkColormap, size);
}

guint gdksharp_gdk_device_get_num_axes_offset (void);

guint
gdksharp_gdk_device_get_num_axes_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, num_axes);
}

guint gdksharp_gdk_device_get_name_offset (void);

guint
gdksharp_gdk_device_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, name);
}

guint gdksharp_gdk_device_get_mode_offset (void);

guint
gdksharp_gdk_device_get_mode_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, mode);
}

guint gdksharp_gdk_device_get_source_offset (void);

guint
gdksharp_gdk_device_get_source_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, source);
}

guint gdksharp_gdk_device_get_num_keys_offset (void);

guint
gdksharp_gdk_device_get_num_keys_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, num_keys);
}

guint gdksharp_gdk_device_get_has_cursor_offset (void);

guint
gdksharp_gdk_device_get_has_cursor_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDevice, has_cursor);
}

void gdksharp_display_override_closed (GType gtype, gpointer cb);

void
gdksharp_display_override_closed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkDisplayClass *)klass)->closed = cb;
}

void gdksharp_display_base_closed (GdkDisplay* display, gboolean is_error);

void
gdksharp_display_base_closed (GdkDisplay* display, gboolean is_error)
{
	GdkDisplayClass *klass = (GdkDisplayClass *) get_threshold_class (G_OBJECT (display));
	if (klass->closed)
		(* klass->closed) (display, is_error);
}
void gdksharp_displaymanager_override_display_opened (GType gtype, gpointer cb);

void
gdksharp_displaymanager_override_display_opened (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkDisplayManagerClass *)klass)->display_opened = cb;
}

void gdksharp_displaymanager_base_display_opened (GdkDisplayManager* display_manager, GdkDisplay* display);

void
gdksharp_displaymanager_base_display_opened (GdkDisplayManager* display_manager, GdkDisplay* display)
{
	GdkDisplayManagerClass *klass = (GdkDisplayManagerClass *) get_threshold_class (G_OBJECT (display_manager));
	if (klass->display_opened)
		(* klass->display_opened) (display_manager, display);
}
guint gdksharp_gdk_dragcontext_get_actions_offset (void);

guint
gdksharp_gdk_dragcontext_get_actions_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, actions);
}

guint gdksharp_gdk_dragcontext_get_start_time_offset (void);

guint
gdksharp_gdk_dragcontext_get_start_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, start_time);
}

guint gdksharp_gdk_dragcontext_get_suggested_action_offset (void);

guint
gdksharp_gdk_dragcontext_get_suggested_action_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, suggested_action);
}

guint gdksharp_gdk_dragcontext_get_source_window_offset (void);

guint
gdksharp_gdk_dragcontext_get_source_window_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, source_window);
}

guint gdksharp_gdk_dragcontext_get_action_offset (void);

guint
gdksharp_gdk_dragcontext_get_action_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, action);
}

guint gdksharp_gdk_dragcontext_get_is_source_offset (void);

guint
gdksharp_gdk_dragcontext_get_is_source_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, is_source);
}

guint gdksharp_gdk_dragcontext_get_protocol_offset (void);

guint
gdksharp_gdk_dragcontext_get_protocol_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, protocol);
}

guint gdksharp_gdk_dragcontext_get_dest_window_offset (void);

guint
gdksharp_gdk_dragcontext_get_dest_window_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkDragContext, dest_window);
}

guint gdksharp_gdk_image_get_type_offset (void);

guint
gdksharp_gdk_image_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, type);
}

guint gdksharp_gdk_image_get_bpp_offset (void);

guint
gdksharp_gdk_image_get_bpp_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, bpp);
}

guint gdksharp_gdk_image_get_visual_offset (void);

guint
gdksharp_gdk_image_get_visual_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, visual);
}

guint gdksharp_gdk_image_get_depth_offset (void);

guint
gdksharp_gdk_image_get_depth_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, depth);
}

guint gdksharp_gdk_image_get_width_offset (void);

guint
gdksharp_gdk_image_get_width_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, width);
}

guint gdksharp_gdk_image_get_byte_order_offset (void);

guint
gdksharp_gdk_image_get_byte_order_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, byte_order);
}

guint gdksharp_gdk_image_get_bpl_offset (void);

guint
gdksharp_gdk_image_get_bpl_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, bpl);
}

guint gdksharp_gdk_image_get_bits_per_pixel_offset (void);

guint
gdksharp_gdk_image_get_bits_per_pixel_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, bits_per_pixel);
}

guint gdksharp_gdk_image_get_height_offset (void);

guint
gdksharp_gdk_image_get_height_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkImage, height);
}

void gdksharp_keymap_override_keys_changed (GType gtype, gpointer cb);

void
gdksharp_keymap_override_keys_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkKeymapClass *)klass)->keys_changed = cb;
}

void gdksharp_keymap_base_keys_changed (GdkKeymap* keymap);

void
gdksharp_keymap_base_keys_changed (GdkKeymap* keymap)
{
	GdkKeymapClass *klass = (GdkKeymapClass *) get_threshold_class (G_OBJECT (keymap));
	if (klass->keys_changed)
		(* klass->keys_changed) (keymap);
}
void gdksharp_keymap_override_direction_changed (GType gtype, gpointer cb);

void
gdksharp_keymap_override_direction_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkKeymapClass *)klass)->direction_changed = cb;
}

void gdksharp_keymap_base_direction_changed (GdkKeymap* keymap);

void
gdksharp_keymap_base_direction_changed (GdkKeymap* keymap)
{
	GdkKeymapClass *klass = (GdkKeymapClass *) get_threshold_class (G_OBJECT (keymap));
	if (klass->direction_changed)
		(* klass->direction_changed) (keymap);
}
void gdksharp_screen_override_size_changed (GType gtype, gpointer cb);

void
gdksharp_screen_override_size_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkScreenClass *)klass)->size_changed = cb;
}

void gdksharp_screen_base_size_changed (GdkScreen* screen);

void
gdksharp_screen_base_size_changed (GdkScreen* screen)
{
	GdkScreenClass *klass = (GdkScreenClass *) get_threshold_class (G_OBJECT (screen));
	if (klass->size_changed)
		(* klass->size_changed) (screen);
}
void gdksharp_screen_override_composited_changed (GType gtype, gpointer cb);

void
gdksharp_screen_override_composited_changed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkScreenClass *)klass)->composited_changed = cb;
}

void gdksharp_screen_base_composited_changed (GdkScreen* screen);

void
gdksharp_screen_base_composited_changed (GdkScreen* screen)
{
	GdkScreenClass *klass = (GdkScreenClass *) get_threshold_class (G_OBJECT (screen));
	if (klass->composited_changed)
		(* klass->composited_changed) (screen);
}
guint gdksharp_gdk_cursor_get_type_offset (void);

guint
gdksharp_gdk_cursor_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkCursor, type);
}

guint gdksharp_gdk_pangoattrembosscolor_get_color_offset (void);

guint
gdksharp_gdk_pangoattrembosscolor_get_color_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkPangoAttrEmbossColor, color);
}

guint gdksharp_gdk_pangoattrembossed_get_embossed_offset (void);

guint
gdksharp_gdk_pangoattrembossed_get_embossed_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkPangoAttrEmbossed, embossed);
}

guint gdksharp_gdk_pangoattrstipple_get_stipple_offset (void);

guint
gdksharp_gdk_pangoattrstipple_get_stipple_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkPangoAttrStipple, stipple);
}

guint gdksharp_gdk_rgbcmap_get_n_colors_offset (void);

guint
gdksharp_gdk_rgbcmap_get_n_colors_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GdkRgbCmap, n_colors);
}

void gdksharp_pixbufloader_override_size_prepared (GType gtype, gpointer cb);

void
gdksharp_pixbufloader_override_size_prepared (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkPixbufLoaderClass *)klass)->size_prepared = cb;
}

void gdksharp_pixbufloader_base_size_prepared (GdkPixbufLoader* loader, int width, int height);

void
gdksharp_pixbufloader_base_size_prepared (GdkPixbufLoader* loader, int width, int height)
{
	GdkPixbufLoaderClass *klass = (GdkPixbufLoaderClass *) get_threshold_class (G_OBJECT (loader));
	if (klass->size_prepared)
		(* klass->size_prepared) (loader, width, height);
}
void gdksharp_pixbufloader_override_closed (GType gtype, gpointer cb);

void
gdksharp_pixbufloader_override_closed (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkPixbufLoaderClass *)klass)->closed = cb;
}

void gdksharp_pixbufloader_base_closed (GdkPixbufLoader* loader);

void
gdksharp_pixbufloader_base_closed (GdkPixbufLoader* loader)
{
	GdkPixbufLoaderClass *klass = (GdkPixbufLoaderClass *) get_threshold_class (G_OBJECT (loader));
	if (klass->closed)
		(* klass->closed) (loader);
}
void gdksharp_pixbufloader_override_area_updated (GType gtype, gpointer cb);

void
gdksharp_pixbufloader_override_area_updated (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkPixbufLoaderClass *)klass)->area_updated = cb;
}

void gdksharp_pixbufloader_base_area_updated (GdkPixbufLoader* loader, int x, int y, int width, int height);

void
gdksharp_pixbufloader_base_area_updated (GdkPixbufLoader* loader, int x, int y, int width, int height)
{
	GdkPixbufLoaderClass *klass = (GdkPixbufLoaderClass *) get_threshold_class (G_OBJECT (loader));
	if (klass->area_updated)
		(* klass->area_updated) (loader, x, y, width, height);
}
void gdksharp_pixbufloader_override_area_prepared (GType gtype, gpointer cb);

void
gdksharp_pixbufloader_override_area_prepared (GType gtype, gpointer cb)
{
	GObjectClass *klass = g_type_class_peek (gtype);
	if (klass == NULL)
		klass = g_type_class_ref (gtype);
	((GdkPixbufLoaderClass *)klass)->area_prepared = cb;
}

void gdksharp_pixbufloader_base_area_prepared (GdkPixbufLoader* loader);

void
gdksharp_pixbufloader_base_area_prepared (GdkPixbufLoader* loader)
{
	GdkPixbufLoaderClass *klass = (GdkPixbufLoaderClass *) get_threshold_class (G_OBJECT (loader));
	if (klass->area_prepared)
		(* klass->area_prepared) (loader);
}
